name: 11. Cleanup All Agents

# Cleanup workflow
on:
  workflow_dispatch:
    inputs:
      batch_size:
        description: 'Number of hosts per batch'
        required: false
        default: '256'
        type: string

jobs:
  prepare:
    runs-on: self-hosted
    outputs:
      batches: ${{ steps.create-batches.outputs.batches }}
      total_hosts: ${{ steps.create-batches.outputs.total_hosts }}
      total_batches: ${{ steps.create-batches.outputs.total_batches }}
    steps:
      - id: create-batches
        run: |
          HOSTS=$(echo "${{ vars.DEPLOYMENT_HOSTS }}" | tr -d '\r' | grep -v '^$')
          TOTAL=$(echo "$HOSTS" | wc -l | xargs)
          echo "total_hosts=$TOTAL" >> $GITHUB_OUTPUT
          BATCH_SIZE=${{ github.event.inputs.batch_size || '256' }}
          TOTAL_BATCHES=$(( (TOTAL + BATCH_SIZE - 1) / BATCH_SIZE ))
          echo "total_batches=$TOTAL_BATCHES" >> $GITHUB_OUTPUT
          BATCHES=$(echo "$HOSTS" | awk -v batch_size=$BATCH_SIZE '
            BEGIN { batch=0; print "[" }
            {
              if (NR % batch_size == 1) {
                if (NR > 1) { print "]" }
                if (NR > 1) { print "," }
                print "["
                printf "\"%s\"", $0
              } else {
                printf ",\"%s\"", $0
              }
            }
            END { if (NR > 0) { print "]" }; print "]" }
          ' | jq -c .)
          echo "batches=$BATCHES" >> $GITHUB_OUTPUT
          echo "📊 Cleaning up /opt/appdynamics from $TOTAL hosts across $TOTAL_BATCHES batches"

  cleanup-batch:
    needs: prepare
    runs-on: self-hosted
    strategy:
      max-parallel: 1
      matrix:
        batch: ${{ fromJson(needs.prepare.outputs.batches) }}
    steps:
      - name: Delete /opt/appdynamics from batch hosts
        run: |
          BATCH_HOSTS='${{ toJson(matrix.batch) }}'
          BATCH_SIZE=$(echo "$BATCH_HOSTS" | jq '. | length')
          SSH_USER="${{ vars.SSH_USER || 'ubuntu' }}"
          echo "🚀 Deleting /opt/appdynamics from batch of $BATCH_SIZE hosts"
          
          FAILED_HOSTS=()
          echo "$BATCH_HOSTS" | jq -r '.[]' | while read HOST; do
            (
              echo "📡 Cleaning up /opt/appdynamics on $HOST"
              mkdir -p ~/.ssh
              echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa_$HOST
              chmod 600 ~/.ssh/id_rsa_$HOST
              
              if ssh -i ~/.ssh/id_rsa_$HOST -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=30 "${SSH_USER}@${HOST}" 'if [ -d "/opt/appdynamics" ]; then sudo rm -rf /opt/appdynamics && echo "✓ Deleted /opt/appdynamics"; else echo "Directory /opt/appdynamics does not exist"; fi'; then
                echo "✅ Completed cleanup on $HOST"
              else
                echo "❌ Failed to clean up $HOST" >&2
                echo "$HOST" >> /tmp/failed_hosts_$$
              fi
              
              rm -f ~/.ssh/id_rsa_$HOST
            ) &
          done
          wait
          
          if [ -f /tmp/failed_hosts_$$ ]; then
            echo "❌ Some hosts failed:"
            cat /tmp/failed_hosts_$$
            rm -f /tmp/failed_hosts_$$
            exit 1
          fi
          echo "✅ Batch cleanup complete"

  summary:
    needs: [prepare, cleanup-batch]
    runs-on: self-hosted
    if: always()
    steps:
      - name: Cleanup Summary
        run: |
          echo "📊 AppDynamics Cleanup Summary"
          echo "===================================="
          echo "Total hosts: ${{ needs.prepare.outputs.total_hosts }}"
          echo "Total batches: ${{ needs.prepare.outputs.total_batches }}"
          echo "Status: ${{ needs.cleanup-batch.result }}"
