name: Deploy AppDynamics Smart Agent

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    strategy:
      matrix:
        host:
          - 172.31.1.243
          - 172.31.1.48
          - 172.31.1.5
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "Host *" > ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
          echo "  UserKnownHostsFile=/dev/null" >> ~/.ssh/config
          chmod 600 ~/.ssh/config

      - name: Copy agent zip to remote host
        run: |
          scp -i ~/.ssh/id_rsa appdsmartagent_64_linux_25.10.0.497.zip ubuntu@${{ matrix.host }}:/tmp/

      - name: Copy config.ini to remote host
        run: |
          scp -i ~/.ssh/id_rsa config.ini ubuntu@${{ matrix.host }}:/tmp/

      - name: Deploy and start agent
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ matrix.host }} << 'EOF'
            cd /tmp
            sudo unzip -o appdsmartagent_64_linux_25.10.0.497.zip -d /opt/appdynamics
            sudo cp config.ini /opt/appdynamics/config.ini
            cd /opt/appdynamics
            sudo ./smartagentctl start --enable-auto-attach --service
          EOF
