name: Deploy AppDynamics Smart Agent (Batched for Large Scale)

on:
  workflow_dispatch:
    inputs:
      batch_size:
        description: 'Number of hosts per batch'
        required: false
        default: '256'
        type: string

jobs:
  prepare:
    runs-on: self-hosted
    outputs:
      batches: ${{ steps.create-batches.outputs.batches }}
      total_hosts: ${{ steps.create-batches.outputs.total_hosts }}
      total_batches: ${{ steps.create-batches.outputs.total_batches }}
    steps:
      - id: create-batches
        run: |
          # Parse hosts and remove empty lines
          HOSTS=$(echo "${{ vars.DEPLOYMENT_HOSTS }}" | tr -d '\r' | grep -v '^$')
          
          # Count total hosts
          TOTAL=$(echo "$HOSTS" | wc -l | xargs)
          echo "total_hosts=$TOTAL" >> $GITHUB_OUTPUT
          
          # Batch size from input or default
          BATCH_SIZE=${{ github.event.inputs.batch_size || '256' }}
          
          # Calculate number of batches needed
          TOTAL_BATCHES=$(( (TOTAL + BATCH_SIZE - 1) / BATCH_SIZE ))
          echo "total_batches=$TOTAL_BATCHES" >> $GITHUB_OUTPUT
          
          # Create batches as JSON array
          BATCHES=$(echo "$HOSTS" | awk -v batch_size=$BATCH_SIZE '
            BEGIN { batch=0; hosts="" }
            {
              if (NR % batch_size == 1) {
                if (hosts != "") {
                  print hosts
                }
                hosts = "\"" $0 "\""
                batch++
              } else {
                hosts = hosts ",\"" $0 "\""
              }
            }
            END { if (hosts != "") print hosts }
          ' | jq -s -c '[.[] | split(",") | map(fromjson)]')
          
          echo "batches=$BATCHES" >> $GITHUB_OUTPUT
          
          echo "📊 Deploying to $TOTAL hosts across $TOTAL_BATCHES batches"

  deploy-batch:
    needs: prepare
    runs-on: self-hosted
    strategy:
      max-parallel: 1  # Run batches sequentially to avoid overwhelming resources
      matrix:
        batch: ${{ fromJson(needs.prepare.outputs.batches) }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to batch hosts
        run: |
          BATCH_HOSTS='${{ toJson(matrix.batch) }}'
          BATCH_SIZE=$(echo "$BATCH_HOSTS" | jq '. | length')
          echo "🚀 Deploying to batch of $BATCH_SIZE hosts"
          
          # Process each host in the batch in parallel using background processes
          echo "$BATCH_HOSTS" | jq -r '.[]' | while read HOST; do
            (
              echo "📡 Starting deployment to $HOST"
              
              # Setup SSH
              mkdir -p ~/.ssh
              echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa_$HOST
              chmod 600 ~/.ssh/id_rsa_$HOST
              
              # Copy files
              scp -i ~/.ssh/id_rsa_$HOST \
                  -o StrictHostKeyChecking=no \
                  -o UserKnownHostsFile=/dev/null \
                  appdsmartagent_64_linux_25.10.0.497.zip ubuntu@$HOST:/tmp/
              
              scp -i ~/.ssh/id_rsa_$HOST \
                  -o StrictHostKeyChecking=no \
                  -o UserKnownHostsFile=/dev/null \
                  config.ini ubuntu@$HOST:/tmp/
              
              # Deploy and start agent
              ssh -i ~/.ssh/id_rsa_$HOST \
                  -o StrictHostKeyChecking=no \
                  -o UserKnownHostsFile=/dev/null \
                  ubuntu@$HOST << 'EOF'
                # Install unzip if not present
                sudo apt-get update -qq
                sudo apt-get install -y unzip
                
                # Extract and deploy
                cd /tmp
                sudo mkdir -p /opt/appdynamics/appdsmartagent
                sudo unzip -o appdsmartagent_64_linux_25.10.0.497.zip -d /opt/appdynamics/appdsmartagent
                sudo cp config.ini /opt/appdynamics/appdsmartagent/config.ini
                
                # Start the agent
                cd /opt/appdynamics/appdsmartagent
                USER="${{ vars.SMARTAGENT_USER }}"
                GROUP="${{ vars.SMARTAGENT_GROUP }}"
                
                if [ -n "$USER" ] && [ -n "$GROUP" ]; then
                  sudo ./smartagentctl start --enable-auto-attach --service --user "$USER" --group "$GROUP"
                else
                  sudo ./smartagentctl start --enable-auto-attach --service
                fi
EOF
              
              # Cleanup
              rm -f ~/.ssh/id_rsa_$HOST
              
              echo "✅ Completed deployment to $HOST"
            ) &
          done
          
          # Wait for all parallel deployments to complete
          wait
          echo "✅ Batch deployment complete"

  summary:
    needs: [prepare, deploy-batch]
    runs-on: self-hosted
    if: always()
    steps:
      - name: Deployment Summary
        run: |
          echo "📊 Deployment Summary"
          echo "===================="
          echo "Total hosts: ${{ needs.prepare.outputs.total_hosts }}"
          echo "Total batches: ${{ needs.prepare.outputs.total_batches }}"
          echo "Status: ${{ needs.deploy-batch.result }}"
