name: Deploy AppDynamics Smart Agent

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - main

jobs:
  prepare:
    runs-on: self-hosted
    outputs:
      hosts: ${{ steps.set-matrix.outputs.hosts }}
    steps:
      - id: set-matrix
        run: |
          HOSTS=$(echo "${{ vars.DEPLOYMENT_HOSTS }}" | tr -d '\r' | grep -v '^$' | xargs -n1 | jq -R . | jq -s -c .)
          echo "hosts=$HOSTS" >> $GITHUB_OUTPUT
  
  deploy:
    needs: prepare
    runs-on: self-hosted
    strategy:
      matrix:
        host: ${{ fromJson(needs.prepare.outputs.hosts) }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "Host *" > ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
          echo "  UserKnownHostsFile=/dev/null" >> ~/.ssh/config
          chmod 600 ~/.ssh/config

      - name: Copy agent zip to remote host
        run: |
          scp -i ~/.ssh/id_rsa appdsmartagent_64_linux_25.10.0.497.zip ubuntu@${{ matrix.host }}:/tmp/

      - name: Copy config.ini to remote host
        run: |
          scp -i ~/.ssh/id_rsa config.ini ubuntu@${{ matrix.host }}:/tmp/

      - name: Deploy and start agent
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ matrix.host }} << 'EOF'
            # Install unzip if not present
            sudo apt-get update -qq
            sudo apt-get install -y unzip
            
            # Extract and deploy
            cd /tmp
            sudo mkdir -p /opt/appdynamics/appdsmartagent
            sudo unzip -o appdsmartagent_64_linux_25.10.0.497.zip -d /opt/appdynamics/appdsmartagent
            sudo cp config.ini /opt/appdynamics/appdsmartagent/config.ini
            
            # Start the agent
            cd /opt/appdynamics/appdsmartagent
            USER="${{ vars.SMARTAGENT_USER }}"
            GROUP="${{ vars.SMARTAGENT_GROUP }}"
            
            if [ -n "$USER" ] && [ -n "$GROUP" ]; then
              sudo ./smartagentctl start --enable-auto-attach --service --user "$USER" --group "$GROUP"
            else
              sudo ./smartagentctl start --enable-auto-attach --service
            fi
          EOF
